name: assets_audio_player_example
description: Demonstrates how to use the assets_audio_player plugin.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_neumorphic_plus: ^3.3.0
  assets_audio_player:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_web_compilers: ^4.0.9
  pedantic: ^1.11.1

flutter:
  uses-material-design: true

  assets:
    - assets/audios/
    - assets/images/
    - assets/fonts/

  fonts:
    - family: AssetAudioPlayer
      fonts:
        - asset: assets/fonts/AssetAudioPlayer.ttf
