name: assets_audio_player_example
description: Demonstrates how to use the assets_audio_player plugin.
publish_to: "none"
version: 3.0.0

environment:
  sdk: ">=2.19.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_neumorphic_plus: ^3.3.0
  rxdart: ^0.27.7
  dio: ^5.4.1
  path_provider: ^2.1.2
  http: ^1.2.1
  provider: ^6.1.2
  file: ^7.0.0
  assets_audio_player:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_web_compilers: ^4.0.9
  pedantic: ^1.11.1

dependency_overrides:
  file: ^7.0.0
  assets_audio_player:
    path: ../

flutter:
  uses-material-design: true

  assets:
    - assets/audios/
    - assets/images/

  fonts:
    - family: AssetAudioPlayer
      fonts:
        - asset: fonts/AssetAudioPlayer.ttf
