name: assets_audio_player
description: Play music/audio stored in assets files directly from Flutter & Network, Radio, LiveStream, Local files. Compatible with Android, iOS, web and macOS.
version: 3.1.1
homepage: https://github.com/florent37/Flutter-AssetsAudioPlayer

environment:
  sdk: ">=2.19.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  rxdart: ^0.27.7
  uuid: ^4.3.3
  http: ">=0.13.0 <2.0.0"
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  plugin:
    platforms:
      android:
        package: com.github.florent37.assets_audio_player
        pluginClass: AssetsAudioPlayerPlugin
        mainClass: AssetsAudioPlayerPlugin
      ios:
        pluginClass: AssetsAudioPlayerPlugin
      macos:
        pluginClass: AssetsAudioPlayerPlugin
      web:
        default_package: assets_audio_player_web
      # moved to assets_audio_player_web
      # web:
      #  pluginClass: AssetsAudioPlayerPlugin
      #  fileName: assets_audio_player_web.dart
